# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'TPLAnimatableIconsExample' do
	pod 'TPLAnimatableIcons', :path => '../../'
end

target 'TPLAnimatableIconsExampleTests' do

end

